allowBuilds:
  core-js: set this to true or false
minimumReleaseAgeExclude:
  - '@expo/config-plugins@57.0.5'
  - '@expo/config-types@57.0.2'
  - '@expo/env@2.4.2'
  - '@expo/json-file@11.0.1'
  - '@expo/metro-runtime@57.0.5'
  - '@expo/plist@0.8.1'
  - '@expo/require-utils@57.0.3'
  - '@expo/schema-utils@57.0.2'
  - '@expo/ui@57.0.6'
  - expo-constants@57.0.5
  - expo-document-picker@57.0.1
  - expo-glass-effect@57.0.1
  - expo-linear-gradient@57.0.1
  - expo-linking@57.0.3
  - expo-print@57.0.1
  - expo-router@57.0.6
  - expo-server@57.0.1
  - expo-sharing@57.0.5
  - expo-status-bar@57.0.1
  - expo-symbols@57.0.1
