import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppShell } from '@/components/AppShell';
import { ProfileHeader } from '@/components/ProfileHeader';
import { birthRecordCompleteness, postpartumRecordCompleteness } from '@/lib/birthPostpartum';
import { useAppStore } from '@/store/useAppStore';
import { colors } from '@/theme';
import { BirthRecord, PostpartumRecord } from '@/types/domain';

const birthFields:{key:keyof BirthRecord;label:string;placeholder:string}[]=[
 {key:'bornAt',label:'Fecha y hora de nacimiento',placeholder:'AAAA-MM-DD HH:MM'}, {key:'gestationalAge',label:'Edad gestacional al nacer',placeholder:'Como aparece en el informe'}, {key:'birthType',label:'Tipo de nacimiento',placeholder:'Como fue documentado'}, {key:'weight',label:'Peso al nacer',placeholder:'Valor y unidad'}, {key:'length',label:'Talla al nacer',placeholder:'Valor y unidad'}, {key:'headCircumference',label:'Perímetro cefálico',placeholder:'Valor y unidad'}, {key:'apgar',label:'Apgar documentado',placeholder:'Valor y minutos, si fue informado'}, {key:'complications',label:'Complicaciones documentadas',placeholder:'Texto del informe o ninguna documentada'}, {key:'neonatalCare',label:'Atención neonatal',placeholder:'Alojamiento, observación, UCIN…'}, {key:'feedingStart',label:'Inicio de alimentación',placeholder:'Pecho, fórmula, mixta; cuándo inició'}, {key:'confirmedBy',label:'Fuente profesional',placeholder:'Hospital, profesional o documento'}
];
const postpartumFields:{key:keyof PostpartumRecord;label:string;placeholder:string}[]=[
 {key:'followUpDate',label:'Fecha de revisión posparto',placeholder:'AAAA-MM-DD'}, {key:'recoveryNotes',label:'Recuperación física',placeholder:'Hechos observados o indicados'}, {key:'feedingNotes',label:'Lactancia o alimentación',placeholder:'Dificultades, apoyo recibido, plan'}, {key:'restAndSupport',label:'Descanso y red de apoyo',placeholder:'Qué apoyo existe o hace falta'}, {key:'emotionalWellbeing',label:'Cómo se ha sentido la mamá',placeholder:'Nota libre, sin diagnóstico automático'}, {key:'medications',label:'Medicamentos indicados',placeholder:'Nombre y pauta tal como fue indicada'}, {key:'professionalInstructions',label:'Indicaciones profesionales',placeholder:'Seguimiento, citas o señales explicadas'}, {key:'confirmedBy',label:'Profesional o documento',placeholder:'Quién confirmó esta información'}
];

export default function BirthPostpartumScreen(){
 const router=useRouter(); const store=useAppStore(); const profile=store.profiles.find(item=>item.id===store.activeProfileId); const child=profile?.stage==='child';
 const [tab,setTab]=useState<'birth'|'postpartum'>('birth'); const [birth,setBirth]=useState<Partial<BirthRecord>>({}); const [postpartum,setPostpartum]=useState<Partial<PostpartumRecord>>({}); const [saved,setSaved]=useState('');
 useEffect(()=>{setBirth(store.birthRecords[store.activeProfileId]??{});setPostpartum(store.postpartumRecords[store.activeProfileId]??{});setSaved('')},[store.activeProfileId,store.birthRecords,store.postpartumRecords]);
 if(!child)return <AppShell><ProfileHeader eyebrow="CONTINUIDAD"/><Text style={styles.title}>Nacimiento y posparto</Text><View style={styles.empty}><MaterialCommunityIcons name="baby-face-outline" size={29} color={colors.muted}/><Text style={styles.emptyTitle}>Selecciona el perfil del bebé</Text><Text style={styles.emptyBody}>Este expediente se vincula al hijo después del nacimiento para mantener continuidad con el embarazo.</Text><Pressable onPress={()=>router.push('/profiles')} style={styles.choose}><Text style={styles.chooseText}>Cambiar perfil</Text></Pressable></View></AppShell>;
 const completeness=tab==='birth'?birthRecordCompleteness(birth as BirthRecord):postpartumRecordCompleteness(postpartum as PostpartumRecord);
 const save=()=>{if(tab==='birth')store.updateBirthRecord(store.activeProfileId,birth);else store.updatePostpartumRecord(store.activeProfileId,postpartum);setSaved('Cambios guardados localmente')};
 const fields=tab==='birth'?birthFields:postpartumFields; const draft=tab==='birth'?birth:postpartum;
 return <AppShell><ProfileHeader eyebrow="CONTINUIDAD"/><Text style={styles.title}>Nacimiento y posparto</Text><Text style={styles.subtitle}>Conserva la historia del nacimiento y el cuidado de la mamá en un mismo lugar, diferenciando notas familiares e información profesional.</Text>
 <View style={styles.tabs}><Pressable onPress={()=>setTab('birth')} style={[styles.tab,tab==='birth'&&styles.tabActive]}><Text style={[styles.tabText,tab==='birth'&&styles.tabTextActive]}>Nacimiento</Text></Pressable><Pressable onPress={()=>setTab('postpartum')} style={[styles.tab,tab==='postpartum'&&styles.tabActive]}><Text style={[styles.tabText,tab==='postpartum'&&styles.tabTextActive]}>Posparto materno</Text></Pressable></View>
 <View style={styles.progress}><View><Text style={styles.progressTitle}>{tab==='birth'?'Expediente de nacimiento':'Seguimiento posparto'}</Text><Text style={styles.progressMeta}>{completeness.completed} de {completeness.total} datos esenciales registrados</Text></View><View style={styles.score}><Text style={styles.scoreText}>{completeness.completed}/{completeness.total}</Text></View></View>
 <View style={styles.form}>{fields.map(field=><View key={field.key}><Text style={styles.label}>{field.label}</Text><TextInput accessibilityLabel={field.label} value={String((draft as Record<string,unknown>)[field.key]??'')} onChangeText={value=>tab==='birth'?setBirth(current=>({...current,[field.key]:value})):setPostpartum(current=>({...current,[field.key]:value}))} placeholder={field.placeholder} multiline={['complications','neonatalCare','recoveryNotes','feedingNotes','restAndSupport','emotionalWellbeing','professionalInstructions'].includes(field.key)} style={[styles.input,['complications','neonatalCare','recoveryNotes','feedingNotes','restAndSupport','emotionalWellbeing','professionalInstructions'].includes(field.key)&&styles.multiline]}/></View>)}</View>
 {saved?<Text style={styles.saved}>{saved}</Text>:null}<Pressable onPress={save} style={styles.save}><MaterialCommunityIcons name="content-save-outline" size={19} color="#FFF"/><Text style={styles.saveText}>Guardar {tab==='birth'?'nacimiento':'seguimiento posparto'}</Text></Pressable>
 <View style={styles.notice}><MaterialCommunityIcons name="information-outline" size={19} color="#795F2E"/><Text style={styles.noticeText}>Emi organiza estos datos, pero no interpreta Apgar, complicaciones, recuperación física ni bienestar emocional. Si existe una preocupación actual, contacta al profesional correspondiente.</Text></View>
 </AppShell>;
}
const styles=StyleSheet.create({title:{color:colors.ink,fontSize:27,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,maxWidth:630},tabs:{flexDirection:'row',backgroundColor:'#ECEBE6',borderRadius:17,padding:4,marginTop:18},tab:{flex:1,minHeight:42,borderRadius:13,alignItems:'center',justifyContent:'center'},tabActive:{backgroundColor:colors.sageDark},tabText:{color:colors.muted,fontSize:9,fontWeight:'900'},tabTextActive:{color:'#FFF'},progress:{backgroundColor:colors.mint,borderRadius:18,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12},progressTitle:{color:colors.ink,fontSize:11,fontWeight:'900'},progressMeta:{color:colors.muted,fontSize:8,marginTop:3},score:{width:42,height:42,borderRadius:15,backgroundColor:colors.white,alignItems:'center',justifyContent:'center'},scoreText:{color:colors.sageDark,fontSize:9,fontWeight:'900'},form:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:21,padding:15,marginTop:12},label:{color:colors.ink,fontSize:9,fontWeight:'900',marginTop:9,marginBottom:5},input:{minHeight:46,borderWidth:1,borderColor:colors.line,borderRadius:14,backgroundColor:colors.canvas,paddingHorizontal:12,color:colors.ink,fontSize:10},multiline:{minHeight:72,paddingTop:11,textAlignVertical:'top'},saved:{color:colors.sageDark,fontSize:9,fontWeight:'800',textAlign:'center',marginTop:10},save:{minHeight:52,borderRadius:17,backgroundColor:colors.sageDark,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:10},saveText:{color:'#FFF',fontSize:10,fontWeight:'900'},notice:{backgroundColor:'#FFF4DD',borderRadius:16,padding:13,flexDirection:'row',gap:9,marginTop:14},noticeText:{color:'#795F2E',fontSize:9,lineHeight:14,flex:1},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:21,padding:28,alignItems:'center',marginTop:20},emptyTitle:{color:colors.ink,fontSize:13,fontWeight:'900',marginTop:8},emptyBody:{color:colors.muted,fontSize:9,lineHeight:14,textAlign:'center',marginTop:4,maxWidth:400},choose:{minHeight:43,borderRadius:14,backgroundColor:colors.sageDark,paddingHorizontal:20,alignItems:'center',justifyContent:'center',marginTop:14},chooseText:{color:'#FFF',fontSize:9,fontWeight:'900'}});
