import { MaterialCommunityIcons } from '@/components/MaterialCommunityIcons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Platform, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAppStore } from '@/store/useAppStore';
import { colors } from '@/theme';
import { useAuth } from '@/context/AuthContext';

export default function ConsentScreen() {
  const router = useRouter(); const { acceptEssentialConsent, demoSession } = useAuth(); const { consentPreferences, setConsentPreference, hasCompletedOnboarding } = useAppStore(); const [accepted, setAccepted] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const proceed = async () => { setBusy(true); setMessage(''); const result = await acceptEssentialConsent(); setBusy(false); if (!result.ok) return setMessage(result.message ?? 'No pudimos guardar tu elección.'); router.replace(hasCompletedOnboarding ? '/home' : '/onboarding'); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.card}><View style={styles.icon}><MaterialCommunityIcons name="shield-check-outline" size={30} color={colors.sageDark} /></View><Text style={styles.eyebrow}>ANTES DE COMENZAR</Text><Text style={styles.title}>Tus datos, bajo tu cuidado</Text><Text style={styles.body}>Emi organiza información familiar y de salud. Tú decides qué funciones usar y puedes cambiar estos permisos después.</Text>
    <View style={styles.required}><MaterialCommunityIcons name="lock-outline" size={20} color={colors.sageDark} /><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Privacidad y términos esenciales</Text><Text style={styles.rowBody}>Entiendo que Emi no diagnostica, no sustituye atención médica y que debo buscar ayuda profesional ante una urgencia.</Text></View><Switch accessibilityLabel="Aceptar privacidad y términos esenciales" value={accepted} onValueChange={setAccepted} trackColor={{ false: '#D8DDD9', true: colors.sage }} /></View>
    <Text style={styles.optional}>PERMISOS OPCIONALES</Text><Permission disabled={demoSession} title="Análisis automático de documentos" body={demoSession ? 'No disponible en modo local. Puedes guardar archivos y anotar datos manualmente.' : 'Solo se enviará contenido cuando tú lo solicites y confirmes.'} value={demoSession ? false : consentPreferences.documentAnalysis} onChange={(v) => setConsentPreference('documentAnalysis', v)} /><Permission disabled={demoSession} title="Asistente con IA externa" body={demoSession ? 'No se usa en modo local. El análisis determinista del dispositivo sigue disponible.' : 'Autoriza resúmenes bajo petición con datos mínimos del perfil. No decide diagnósticos ni urgencias.'} value={demoSession ? false : consentPreferences.aiAssistant} onChange={(v) => setConsentPreference('aiAssistant', v)} /><Permission title="Registro por voz" body="Conservaremos únicamente el texto que confirmes." value={consentPreferences.voice} onChange={(v) => setConsentPreference('voice', v)} /><Permission disabled={demoSession} title="Mejorar Emi" body={demoSession ? 'El modo local no envía métricas de uso.' : 'Métricas sin nombres, notas clínicas ni documentos.'} value={demoSession ? false : consentPreferences.productAnalytics} onChange={(v) => setConsentPreference('productAnalytics', v)} />
    {message ? <Text style={styles.error}>{message}</Text> : null}<Pressable accessibilityRole="button" disabled={!accepted || busy} onPress={proceed} style={[styles.primary, (!accepted || busy) && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Preparando tu espacio…' : 'Aceptar y continuar'}</Text><MaterialCommunityIcons name="arrow-right" size={18} color="#FFF" /></Pressable><Text style={styles.foot}>Puedes retirar los permisos opcionales desde Privacidad. La atención inmediata nunca debe depender de Emi.</Text></View></ScrollView></SafeAreaView>;
}
function Permission({ title, body, value, onChange, disabled }: { title: string; body: string; value: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <View style={styles.permission}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowBody}>{body}</Text></View><Switch accessibilityLabel={title} disabled={disabled} value={value} onValueChange={onChange} trackColor={{ false: '#D8DDD9', true: colors.sage }} /></View>; }
const serif = Platform.select({ web: 'Georgia, Times New Roman, serif', ios: 'Georgia', android: 'serif' });
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F6F2EB' }, page: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: 20 }, card: { width: '100%', maxWidth: 560, backgroundColor: '#FCFAF6', borderWidth: 1, borderColor: '#E8E2D9', borderRadius: 28, padding: 26 }, icon: { width: 56, height: 56, borderRadius: 21, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, eyebrow: { color: colors.sageDark, fontSize: 8, fontWeight: '900', letterSpacing: 1.3, textAlign: 'center', marginTop: 13 }, title: { color: colors.ink, fontFamily: serif, fontSize: 31, fontWeight: '700', textAlign: 'center', marginTop: 7 }, body: { color: colors.muted, fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 8 }, required: { flexDirection: 'row', gap: 11, alignItems: 'center', borderRadius: 18, backgroundColor: colors.mint, padding: 14, marginTop: 21 }, optional: { color: colors.muted, fontSize: 8, fontWeight: '900', letterSpacing: 1, marginTop: 20, marginBottom: 3 }, permission: { flexDirection: 'row', gap: 12, alignItems: 'center', minHeight: 67, borderBottomWidth: 1, borderBottomColor: colors.line }, rowTitle: { color: colors.ink, fontSize: 10, fontWeight: '900' }, rowBody: { color: colors.muted, fontSize: 8, lineHeight: 13, marginTop: 3 }, error: { color: '#8D4747', backgroundColor: '#FBEAEA', borderRadius: 13, padding: 10, fontSize: 8, lineHeight: 13, marginTop: 12 }, primary: { height: 53, borderRadius: 17, backgroundColor: colors.sageDark, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, marginTop: 21 }, disabled: { opacity: .4 }, primaryText: { color: '#FFF', fontSize: 11, fontWeight: '900' }, foot: { color: colors.muted, fontSize: 7, lineHeight: 11, textAlign: 'center', marginTop: 11 } });
