import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppShell } from '@/components/AppShell';
import { ProfileHeader } from '@/components/ProfileHeader';
import { feedingDaySummary, feedingHistory, FeedingType } from '@/lib/feedingHistory';
import { useAppStore } from '@/store/useAppStore';
import { colors } from '@/theme';

const typeMeta:Record<FeedingType,{label:string;icon:keyof typeof MaterialCommunityIcons.glyphMap;color:string}>={breast:{label:'Lactancia',icon:'mother-nurse',color:'#F4D3C1'},bottle:{label:'Biberón',icon:'baby-bottle-outline',color:'#E8E1D5'},extraction:{label:'Extracción',icon:'cup-water',color:'#DCECE6'},solid:{label:'Alimento',icon:'food-apple-outline',color:'#F4E5C9'},other:{label:'Otro',icon:'food-outline',color:'#ECEBE6'}};
export default function FeedingScreen(){
 const router=useRouter(); const {events,activeProfileId,activeSessions}=useAppStore(); const records=feedingHistory(events,activeProfileId); const summary=feedingDaySummary(records,new Date());
 return <AppShell><ProfileHeader eyebrow="ALIMENTACIÓN"/><Text style={styles.title}>Lactancia y alimentación</Text><Text style={styles.subtitle}>Registra en segundos y revisa únicamente lo que ocurrió. Los volúmenes de unidades distintas nunca se mezclan.</Text>
 {activeSessions.feeding?<Pressable onPress={()=>router.push({pathname:'/track/[kind]',params:{kind:'feeding'}})} style={styles.active}><View style={styles.pulse}/><View style={{flex:1}}><Text style={styles.activeTop}>TOMA EN CURSO</Text><Text style={styles.activeTitle}>{activeSessions.feeding.label}</Text></View><Text style={styles.open}>Abrir</Text></Pressable>:null}
 <View style={styles.quick}>{(['breast','bottle','extraction','solid'] as FeedingType[]).map(type=>{const meta=typeMeta[type];return <Pressable key={type} onPress={()=>router.push({pathname:'/track/[kind]',params:{kind:'feeding'}})} style={styles.quickItem}><View style={[styles.quickIcon,{backgroundColor:meta.color}]}><MaterialCommunityIcons name={meta.icon} size={22} color={colors.ink}/></View><Text style={styles.quickText}>{meta.label}</Text></Pressable>})}</View>
 <Text style={styles.section}>RESUMEN DE HOY</Text><View style={styles.summary}><Summary value={summary.breast} label="Lactancia"/><Summary value={summary.bottles} label="Biberones"/><Summary value={summary.extractions} label="Extracciones"/><Summary value={summary.solids} label="Alimentos"/></View>
 {summary.totals.length?<View style={styles.totals}><Text style={styles.totalTitle}>Cantidades anotadas hoy</Text><Text style={styles.totalValue}>{summary.totals.map(total=>`${total.value} ${total.unit}`).join(' · ')}</Text><Text style={styles.totalNote}>Suma matemática de registros con la misma unidad; no estima ingesta ni producción.</Text></View>:null}
 <Text style={styles.section}>HISTORIAL RECIENTE</Text>{records.length?<View style={styles.list}>{records.slice(0,12).map(record=>{const meta=typeMeta[record.type];return <Pressable key={record.id} onPress={()=>router.push({pathname:'/track/[kind]',params:{kind:'feeding'}})} style={styles.record}><View style={[styles.recordIcon,{backgroundColor:meta.color}]}><MaterialCommunityIcons name={meta.icon} size={19} color={colors.ink}/></View><View style={{flex:1}}><View style={styles.recordHead}><Text style={styles.recordTitle}>{record.food||record.title}</Text><Text style={styles.time}>{new Date(record.occurredAt).toLocaleString('es-MX',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</Text></View><Text style={styles.detail}>{record.amount!==undefined&&record.unit?`${record.amount} ${record.unit}`:record.durationMinutes?`${record.durationMinutes} min`:record.detail}</Text>{record.reaction?<Text style={styles.reaction}>Reacción observada: {record.reaction}</Text>:null}<Text style={styles.source}>{record.source==='professional'?'Información profesional':record.source==='document'?'Documento confirmado':'Registrado por la familia'}</Text></View><MaterialCommunityIcons name="chevron-right" size={18} color={colors.muted}/></Pressable>})}</View>:<View style={styles.empty}><MaterialCommunityIcons name="mother-nurse" size={27} color={colors.muted}/><Text style={styles.emptyTitle}>Aún no hay registros</Text><Text style={styles.emptyBody}>Puedes comenzar con un toque y completar detalles después.</Text></View>}
 <View style={styles.notice}><MaterialCommunityIcons name="information-outline" size={19} color="#795F2E"/><Text style={styles.noticeText}>La duración del pecho y la cantidad extraída no indican por sí solas cuánto consumió el bebé. Comparte dudas de alimentación con el profesional correspondiente.</Text></View>
 </AppShell>;
}
function Summary({value,label}:{value:number;label:string}){return <View style={styles.summaryItem}><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>}
const styles=StyleSheet.create({title:{color:colors.ink,fontSize:27,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,maxWidth:610},active:{minHeight:58,borderRadius:18,backgroundColor:colors.mint,borderWidth:1,borderColor:'#BED4CD',flexDirection:'row',alignItems:'center',gap:10,padding:13,marginTop:16},pulse:{width:10,height:10,borderRadius:5,backgroundColor:colors.sageDark},activeTop:{color:colors.sageDark,fontSize:7,fontWeight:'900',letterSpacing:.8},activeTitle:{color:colors.ink,fontSize:10,fontWeight:'900',marginTop:2},open:{color:colors.sageDark,fontSize:9,fontWeight:'900'},quick:{flexDirection:'row',gap:7,marginTop:12,flexWrap:'wrap'},quickItem:{flex:1,minWidth:105,minHeight:82,borderRadius:18,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',gap:7},quickIcon:{width:38,height:38,borderRadius:15,alignItems:'center',justifyContent:'center'},quickText:{color:colors.ink,fontSize:8,fontWeight:'900'},section:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:22,marginBottom:8},summary:{flexDirection:'row',gap:7},summaryItem:{flex:1,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:16,padding:11},summaryValue:{color:colors.ink,fontSize:19,fontWeight:'900'},summaryLabel:{color:colors.muted,fontSize:7,marginTop:2},totals:{backgroundColor:colors.mint,borderRadius:16,padding:13,marginTop:9},totalTitle:{color:colors.sageDark,fontSize:8,fontWeight:'900'},totalValue:{color:colors.ink,fontSize:16,fontWeight:'900',marginTop:4},totalNote:{color:colors.muted,fontSize:7,lineHeight:11,marginTop:4},list:{gap:8},record:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',gap:10},recordIcon:{width:40,height:40,borderRadius:15,alignItems:'center',justifyContent:'center'},recordHead:{flexDirection:'row',justifyContent:'space-between',gap:8},recordTitle:{color:colors.ink,fontSize:10,fontWeight:'900',flex:1},time:{color:colors.muted,fontSize:7},detail:{color:colors.muted,fontSize:8,lineHeight:13,marginTop:4},reaction:{color:'#8B5D2F',fontSize:7,fontWeight:'800',marginTop:3},source:{color:colors.sageDark,fontSize:7,fontWeight:'800',marginTop:5},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:24,alignItems:'center'},emptyTitle:{color:colors.ink,fontSize:11,fontWeight:'900',marginTop:7},emptyBody:{color:colors.muted,fontSize:8,marginTop:3},notice:{backgroundColor:'#FFF4DD',borderRadius:16,padding:13,flexDirection:'row',gap:9,marginTop:16},noticeText:{color:'#795F2E',fontSize:9,lineHeight:14,flex:1}});
