import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppShell } from '@/components/AppShell';
import { ProfileHeader } from '@/components/ProfileHeader';
import { growthSeries, GrowthPoint, milestoneEvents, seriesChange } from '@/lib/growth';
import { useAppStore } from '@/store/useAppStore';
import { colors } from '@/theme';

export default function GrowthScreen() {
  const router = useRouter(); const { events, activeProfileId } = useAppStore();
  const weights = growthSeries(events, activeProfileId, 'weight'); const heights = growthSeries(events, activeProfileId, 'height'); const milestones = milestoneEvents(events, activeProfileId);
  return <AppShell><ProfileHeader eyebrow="CRECIMIENTO Y DESARROLLO" /><Text style={styles.title}>Su historia, medida con cuidado</Text><Text style={styles.subtitle}>Esta vista ordena mediciones confirmadas por fecha. No calcula percentiles ni determina si un valor es normal.</Text>
    <View style={styles.actions}><Pressable onPress={() => router.push({ pathname: '/track/[kind]', params: { kind: 'growth' } })} style={styles.primary}><MaterialCommunityIcons name="plus" size={19} color="#FFF" /><Text style={styles.primaryText}>Agregar medición o hito</Text></Pressable><Pressable onPress={() => router.push('/report')} style={styles.secondary}><MaterialCommunityIcons name="file-document-outline" size={19} color={colors.sageDark} /><Text style={styles.secondaryText}>Preparar consulta</Text></Pressable></View>
    <MetricPanel title="Peso" icon="scale-bathroom" points={weights} /><MetricPanel title="Talla" icon="human-male-height" points={heights} />
    <Text style={styles.section}>DESARROLLO</Text><Pressable accessibilityRole="link" onPress={() => router.push('/development')} style={styles.developmentLink}><View style={styles.star}><MaterialCommunityIcons name="star-outline" size={18} color={colors.sageDark} /></View><View style={{flex:1}}><Text style={styles.milestoneTitle}>Descubrimientos y habilidades</Text><Text style={styles.context}>{milestones.length?`${milestones.length} ${milestones.length===1?'hito observado':'hitos observados'} · revisar por áreas`:'Registra hitos sin convertirlos en logros obligatorios.'}</Text></View><MaterialCommunityIcons name="chevron-right" size={19} color={colors.muted}/></Pressable>
    <View style={styles.notice}><MaterialCommunityIcons name="information-outline" size={19} color="#795F2E" /><Text style={styles.noticeText}>Para incorporar curvas o percentiles se necesita elegir un estándar clínico apropiado, validar los datos requeridos y conservar quién realizó cada medición.</Text></View>
  </AppShell>;
}

function MetricPanel({ title, icon, points }: { title: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; points: GrowthPoint[] }) {
  const change = seriesChange(points); const values = points.map((point) => point.value); const min = Math.min(...values); const max = Math.max(...values); const spread = Math.max(.1, max - min);
  return <><Text style={styles.section}>{title.toUpperCase()}</Text>{points.length ? <View style={styles.panel}><View style={styles.panelHead}><View style={styles.metricIcon}><MaterialCommunityIcons name={icon} size={21} color={colors.sageDark} /></View><View style={{ flex: 1 }}><Text style={styles.latest}>{points.at(-1)!.value} {points.at(-1)!.unit}</Text><Text style={styles.meta}>Última medición · {new Date(points.at(-1)!.date).toLocaleDateString('es-MX', { day: 'numeric', month: 'short', year: 'numeric' })}</Text></View>{change ? <View style={styles.change}><Text style={styles.changeValue}>{change.delta >= 0 ? '+' : ''}{change.delta} {points[0].unit}</Text><Text style={styles.changeLabel}>entre {change.count} mediciones</Text></View> : null}</View><View style={styles.chart}>{points.slice(-8).map((point) => { const height = points.length === 1 ? 55 : 18 + ((point.value - min) / spread) * 72; return <View key={point.id} style={styles.column}><Text style={styles.pointValue}>{point.value}</Text><View style={styles.barTrack}><View style={[styles.bar, { height: `${height}%` }]} /></View><Text style={styles.date}>{new Date(point.date).toLocaleDateString('es-MX', { day: 'numeric', month: 'short' })}</Text></View>; })}</View><Text style={styles.caption}>Escala relativa a estas mediciones · no es una curva clínica</Text><View style={styles.rows}>{points.slice().reverse().slice(0, 4).map((point) => <View key={point.id} style={styles.row}><Text style={styles.rowDate}>{new Date(point.date).toLocaleDateString('es-MX')}</Text><Text style={styles.rowValue}>{point.value} {point.unit}</Text><Text style={styles.rowSource}>{point.measuredBy || (point.source === 'professional' ? 'Profesional' : 'Familia')}</Text></View>)}</View></View> : <Empty text={`Aún no hay mediciones de ${title.toLocaleLowerCase('es-MX')} con una unidad reconocida.`} />}</>;
}
function Empty({ text }: { text: string }) { return <View style={styles.empty}><MaterialCommunityIcons name="chart-line-variant" size={25} color={colors.muted} /><Text style={styles.emptyText}>{text}</Text></View>; }

const styles = StyleSheet.create({ title:{color:colors.ink,fontSize:27,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,maxWidth:610},actions:{flexDirection:'row',gap:8,marginTop:18},primary:{flex:1,minHeight:48,backgroundColor:colors.sageDark,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:'#FFF',fontSize:9,fontWeight:'900'},secondary:{flex:1,minHeight:48,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},secondaryText:{color:colors.sageDark,fontSize:9,fontWeight:'900'},section:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:23,marginBottom:8},panel:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:15},panelHead:{flexDirection:'row',alignItems:'center',gap:10},metricIcon:{width:40,height:40,borderRadius:15,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},latest:{color:colors.ink,fontSize:17,fontWeight:'900'},meta:{color:colors.muted,fontSize:8,marginTop:3},change:{backgroundColor:colors.mint,borderRadius:11,padding:8,alignItems:'flex-end'},changeValue:{color:colors.sageDark,fontSize:9,fontWeight:'900'},changeLabel:{color:colors.muted,fontSize:7,marginTop:2},chart:{height:145,flexDirection:'row',alignItems:'flex-end',gap:8,marginTop:15},column:{flex:1,alignItems:'center',height:'100%'},pointValue:{color:colors.muted,fontSize:7,height:14},barTrack:{flex:1,width:'70%',backgroundColor:'#EEF1EC',borderRadius:7,justifyContent:'flex-end',overflow:'hidden'},bar:{width:'100%',backgroundColor:colors.sage,borderRadius:7},date:{color:colors.muted,fontSize:7,marginTop:5},caption:{color:colors.muted,fontSize:7,textAlign:'center',marginTop:9},rows:{marginTop:10,borderTopWidth:1,borderTopColor:colors.line},row:{minHeight:35,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:colors.line},rowDate:{flex:1,color:colors.muted,fontSize:8},rowValue:{color:colors.ink,fontSize:9,fontWeight:'900'},rowSource:{width:95,color:colors.muted,fontSize:7,textAlign:'right'},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:22,alignItems:'center',gap:8},emptyText:{color:colors.muted,fontSize:9,lineHeight:14,textAlign:'center',maxWidth:420},developmentLink:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',gap:10},star:{width:37,height:37,borderRadius:14,backgroundColor:colors.mint,alignItems:'center',justifyContent:'center'},milestoneTitle:{color:colors.ink,fontSize:10,fontWeight:'900'},context:{color:colors.muted,fontSize:8,lineHeight:13,marginTop:5},notice:{backgroundColor:'#FFF4DD',borderRadius:16,padding:13,flexDirection:'row',gap:9,marginTop:17},noticeText:{color:'#795F2E',fontSize:9,lineHeight:14,flex:1} });
