import { MaterialCommunityIcons } from '@/components/MaterialCommunityIcons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppShell } from '@/components/AppShell';
import { ProfileHeader } from '@/components/ProfileHeader';
import { treatmentCompleteness, treatmentHistory } from '@/lib/healthHistory';
import { useAppStore } from '@/store/useAppStore';
import { colors } from '@/theme';

export default function HealthHistoryScreen() {
  const router = useRouter(); const { events, activeProfileId } = useAppStore(); const [filter, setFilter] = useState<'all' | 'medicine' | 'vaccine'>('all');
  const all = treatmentHistory(events, activeProfileId); const records = filter === 'all' ? all : all.filter((record) => record.type === filter);
  return <AppShell><ProfileHeader eyebrow="SALUD Y CUIDADOS" /><Text style={styles.title}>Medicamentos y vacunas</Text><Text style={styles.subtitle}>Un historial fiel a lo registrado. Emi no recomienda medicamentos, calcula dosis ni completa esquemas de vacunación.</Text>
    <Pressable onPress={() => router.push({ pathname: '/track/[kind]', params: { kind: 'medicine' } })} style={styles.add}><MaterialCommunityIcons name="plus" size={19} color="#FFF" /><Text style={styles.addText}>Agregar medicamento o vacuna</Text></Pressable>
    <View style={styles.filters}>{([['all','Todo'],['medicine','Medicamentos'],['vaccine','Vacunas']] as const).map(([id,label]) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: filter === id }} key={id} onPress={() => setFilter(id)} style={[styles.filter, filter === id && styles.filterActive]}><Text style={[styles.filterText, filter === id && styles.filterTextActive]}>{label}</Text></Pressable>)}</View>
    <View style={styles.summary}><Summary value={all.filter((item) => item.type === 'medicine').length} label="Medicamentos" /><Summary value={all.filter((item) => item.type === 'vaccine').length} label="Vacunas" /><Summary value={all.filter((item) => item.source === 'document').length} label="Documentales" /></View>
    <Text style={styles.section}>HISTORIAL</Text>{records.length ? <View style={styles.list}>{records.map((record) => { const completeness = treatmentCompleteness(record); return <Pressable accessibilityRole="link" onPress={() => router.push({ pathname: '/track/[kind]', params: { kind: 'medicine' } })} key={record.id} style={styles.record}><View style={[styles.icon, { backgroundColor: record.type === 'vaccine' ? '#E7E2F2' : '#E8EFEA' }]}><MaterialCommunityIcons name={record.type === 'vaccine' ? 'needle' : 'pill'} size={20} color={colors.ink} /></View><View style={{ flex: 1 }}><View style={styles.recordHead}><Text style={styles.recordName}>{record.name}</Text><Text style={styles.date}>{new Date(record.occurredAt).toLocaleDateString('es-MX', { day: 'numeric', month: 'short', year: 'numeric' })}</Text></View>{record.type === 'medicine' ? <Text style={styles.detail}>{[record.dose, record.route, record.indicatedBy && `Indicado por ${record.indicatedBy}`].filter(Boolean).join(' · ') || record.detail}</Text> : <Text style={styles.detail}>{[record.lot && `Lote ${record.lot}`, record.reaction && `Reacción: ${record.reaction}`].filter(Boolean).join(' · ') || record.detail}</Text>}<View style={styles.metaRow}><Text style={styles.source}>{record.source === 'document' ? 'Documento confirmado' : record.source === 'professional' ? 'Información profesional' : 'Registrado por la familia'}</Text>{!completeness.complete ? <Text style={styles.incomplete}>Falta confirmar: {completeness.missing.join(', ')}</Text> : null}</View></View><MaterialCommunityIcons name="chevron-right" size={18} color={colors.muted} /></Pressable>; })}</View> : <View style={styles.empty}><MaterialCommunityIcons name="clipboard-text-clock-outline" size={27} color={colors.muted} /><Text style={styles.emptyTitle}>Sin registros en esta sección</Text><Text style={styles.emptyText}>Agrega únicamente lo que fue administrado o confirmado.</Text></View>}
    <View style={styles.notice}><MaterialCommunityIcons name="shield-check-outline" size={19} color="#795F2E" /><Text style={styles.noticeText}>Los recordatorios de vacunas por país y edad se habilitarán únicamente con un catálogo oficial versionado y validación clínica local.</Text></View>
  </AppShell>;
}

function Summary({ value, label }: { value: number; label: string }) { return <View style={styles.summaryItem}><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ title:{color:colors.ink,fontSize:27,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,maxWidth:620},add:{minHeight:50,borderRadius:17,backgroundColor:colors.sageDark,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,marginTop:18},addText:{color:'#FFF',fontSize:10,fontWeight:'900'},filters:{flexDirection:'row',backgroundColor:'#ECEBE6',borderRadius:16,padding:4,marginTop:12},filter:{flex:1,minHeight:38,borderRadius:12,alignItems:'center',justifyContent:'center'},filterActive:{backgroundColor:colors.white},filterText:{color:colors.muted,fontSize:8,fontWeight:'800'},filterTextActive:{color:colors.ink},summary:{flexDirection:'row',gap:7,marginTop:12},summaryItem:{flex:1,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:16,padding:11},summaryValue:{color:colors.ink,fontSize:19,fontWeight:'900'},summaryLabel:{color:colors.muted,fontSize:7,marginTop:2},section:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:22,marginBottom:8},list:{gap:8},record:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',gap:10},icon:{width:40,height:40,borderRadius:15,alignItems:'center',justifyContent:'center'},recordHead:{flexDirection:'row',justifyContent:'space-between',gap:8},recordName:{color:colors.ink,fontSize:10,fontWeight:'900',flex:1},date:{color:colors.muted,fontSize:7},detail:{color:colors.muted,fontSize:8,lineHeight:13,marginTop:4},metaRow:{marginTop:6,gap:3},source:{color:colors.sageDark,fontSize:7,fontWeight:'800'},incomplete:{color:'#946626',fontSize:7,fontWeight:'800'},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:24,alignItems:'center'},emptyTitle:{color:colors.ink,fontSize:11,fontWeight:'900',marginTop:7},emptyText:{color:colors.muted,fontSize:8,marginTop:3},notice:{backgroundColor:'#FFF4DD',borderRadius:16,padding:13,flexDirection:'row',gap:9,marginTop:16},noticeText:{color:'#795F2E',fontSize:9,lineHeight:14,flex:1} });
