import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, shadowLifted, webDepth } from '@/theme';

export function BreastfeedingChoice({ visible, onClose, onRegister, onTimer, onDetails }: { visible: boolean; onClose: () => void; onRegister: () => void; onTimer: () => void; onDetails: () => void }) {
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable accessibilityRole="button" accessibilityLabel="Cerrar opciones de lactancia" onPress={onClose} style={styles.backdrop}><Pressable onPress={() => undefined} style={styles.card}>
    <View style={styles.head}><View style={styles.icon}><MaterialCommunityIcons name="mother-nurse" size={25} color={colors.ink} /></View><View style={{ flex: 1 }}><Text style={styles.title}>Registrar lactancia</Text><Text style={styles.subtitle}>Elige cuánto quieres registrar ahora.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Cerrar" onPress={onClose}><MaterialCommunityIcons name="close" size={21} color={colors.muted} /></Pressable></View>
    <Choice icon="check-circle-outline" title="Registrar ahora" body="Guarda una toma de pecho sin medir el tiempo." onPress={onRegister} primary />
    <Choice icon="timer-outline" title="Iniciar cronómetro" body="Mide la duración hasta que decidas finalizar." onPress={onTimer} />
    <Choice icon="tune-variant" title="Agregar detalles" body="Biberón, extracción, alimento u otra información." onPress={onDetails} />
    <Text style={styles.note}>El tiempo y el lado son opcionales. Siempre podrás editar el registro después.</Text>
  </Pressable></Pressable></Modal>;
}

function Choice({ icon, title, body, onPress, primary }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; title: string; body: string; onPress: () => void; primary?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={[styles.choice, primary && styles.choicePrimary]}><View style={[styles.choiceIcon, primary && styles.choiceIconPrimary]}><MaterialCommunityIcons name={icon} size={20} color={primary ? '#FFF' : colors.sageDark} /></View><View style={{ flex: 1 }}><Text style={[styles.choiceTitle, primary && styles.choiceTitlePrimary]}>{title}</Text><Text style={[styles.choiceBody, primary && styles.choiceBodyPrimary]}>{body}</Text></View><MaterialCommunityIcons name="chevron-right" size={20} color={primary ? '#FFF' : colors.muted} /></Pressable>; }
const serif = Platform.select({ web: 'Georgia, Times New Roman, serif', ios: 'Georgia', android: 'serif' });
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(25,43,39,.48)', justifyContent: 'center', alignItems: 'center', padding: 20 }, card: { width: '100%', maxWidth: 430, backgroundColor: colors.card, borderRadius: 30, padding: 20, ...shadowLifted, ...Platform.select({ web: { boxShadow: webDepth.raised } as any }) }, head: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 13 }, icon: { width: 50, height: 50, borderRadius: 19, backgroundColor: '#F4D3C1', borderWidth: 1, borderColor: 'rgba(255,255,255,.74)', alignItems: 'center', justifyContent: 'center', ...Platform.select({ web: { boxShadow: webDepth.control } as any }) }, title: { color: colors.ink, fontFamily: serif, fontSize: 20, fontWeight: '700' }, subtitle: { color: colors.muted, fontSize: 8, marginTop: 3 }, choice: { minHeight: 72, borderRadius: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: '#FFF', padding: 11, marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 11, ...Platform.select({ web: { boxShadow: webDepth.soft, transitionDuration: '150ms' } as any }) }, choicePrimary: { backgroundColor: colors.sageDeep, borderColor: colors.sageDeep }, choiceIcon: { width: 41, height: 41, borderRadius: 15, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center', ...Platform.select({ web: { boxShadow: webDepth.control } as any }) }, choiceIconPrimary: { backgroundColor: 'rgba(255,255,255,.14)' }, choiceTitle: { color: colors.ink, fontSize: 10, fontWeight: '900' }, choiceTitlePrimary: { color: '#FFF' }, choiceBody: { color: colors.muted, fontSize: 8, lineHeight: 12, marginTop: 3 }, choiceBodyPrimary: { color: '#DCEAE6' }, note: { color: colors.muted, fontSize: 7, lineHeight: 12, textAlign: 'center', marginTop: 12 } });
