import { MaterialCommunityIcons } from '@/components/MaterialCommunityIcons';
import { Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, shadowLifted, webDepth } from '@/theme';

export type CareChoiceKind = 'sleep' | 'diaper' | 'comfort';
type Choice = { id: string; title: string; body: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; primary?: boolean };
const content: Record<CareChoiceKind, { title: string; subtitle: string; icon: keyof typeof MaterialCommunityIcons.glyphMap; color: string; note: string; choices: Choice[] }> = {
  sleep: { title: 'Registrar sueño', subtitle: 'Elige lo que está ocurriendo.', icon: 'weather-night', color: '#DDD9ED', note: 'Puedes corregir el inicio, final o duración más tarde.', choices: [{ id: 'timer', title: 'Iniciar cronómetro', body: 'Comienza a medir el sueño ahora.', icon: 'timer-outline', primary: true }, { id: 'previous', title: 'Registrar sin cronómetro', body: 'Añade después un periodo y su duración.', icon: 'clock-plus-outline' }, { id: 'wake', title: 'Despertó ahora', body: 'Guarda únicamente el despertar.', icon: 'weather-sunset-up' }] },
  diaper: { title: 'Registrar pañal', subtitle: 'Lo común se guarda con un toque.', icon: 'water-outline', color: '#DCECE6', note: 'Color, consistencia y notas son siempre opcionales.', choices: [{ id: 'wet', title: 'Mojado', body: 'Guarda un pañal mojado.', icon: 'water', primary: true }, { id: 'bowel', title: 'Evacuación', body: 'Guarda una evacuación sin más preguntas.', icon: 'circle-outline' }, { id: 'both', title: 'Ambos', body: 'Mojado y evacuación en un registro.', icon: 'check-all' }, { id: 'details', title: 'Agregar detalles', body: 'Color, consistencia u otra observación.', icon: 'tune-variant' }] },
  comfort: { title: 'Registrar confort', subtitle: 'Anota lo observado, sin atribuir causas.', icon: 'heart-outline', color: '#F3E4DC', note: 'El contexto puede añadirse después; no se interpreta automáticamente.', choices: [{ id: 'irritability', title: 'Irritabilidad', body: 'Guarda el episodio ahora.', icon: 'emoticon-sad-outline', primary: true }, { id: 'gas', title: 'Gases', body: 'Guarda el episodio ahora.', icon: 'weather-windy' }, { id: 'regurgitation', title: 'Regurgitación', body: 'Guarda lo observado ahora.', icon: 'cup-water' }, { id: 'details', title: 'Rutina o detalles', body: 'Añade contexto y respuesta observada.', icon: 'tune-variant' }] }
};

export function CareQuickChoice({ kind, visible, onClose, onChoose }: { kind: CareChoiceKind; visible: boolean; onClose: () => void; onChoose: (choice: string) => void }) {
  const item = content[kind];
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable accessibilityRole="button" accessibilityLabel={`Cerrar opciones de ${kind}`} onPress={onClose} style={styles.backdrop}><Pressable onPress={() => undefined} style={styles.card}>
    <View style={styles.head}><View style={[styles.icon, { backgroundColor: item.color }]}><MaterialCommunityIcons name={item.icon} size={24} color={colors.ink} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{item.title}</Text><Text style={styles.subtitle}>{item.subtitle}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Cerrar" onPress={onClose}><MaterialCommunityIcons name="close" size={21} color={colors.muted} /></Pressable></View>
    {item.choices.map((choice) => <Pressable accessibilityRole="button" accessibilityLabel={choice.title} key={choice.id} onPress={() => onChoose(choice.id)} style={[styles.choice, choice.primary && styles.primary]}><View style={[styles.choiceIcon, choice.primary && styles.primaryIcon]}><MaterialCommunityIcons name={choice.icon} size={19} color={choice.primary ? '#FFF' : colors.sageDark} /></View><View style={{ flex: 1 }}><Text style={[styles.choiceTitle, choice.primary && styles.primaryTitle]}>{choice.title}</Text><Text style={[styles.choiceBody, choice.primary && styles.primaryBody]}>{choice.body}</Text></View><MaterialCommunityIcons name="chevron-right" size={19} color={choice.primary ? '#FFF' : colors.muted} /></Pressable>)}
    <Text style={styles.note}>{item.note}</Text>
  </Pressable></Pressable></Modal>;
}
const serif = Platform.select({ web: 'Georgia, Times New Roman, serif', ios: 'Georgia', android: 'serif' });
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(25,43,39,.48)', justifyContent: 'center', alignItems: 'center', padding: 20 }, card: { width: '100%', maxWidth: 430, backgroundColor: colors.card, borderRadius: 30, padding: 20, ...shadowLifted, ...Platform.select({ web: { boxShadow: webDepth.raised } as any }) }, head: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 13 }, icon: { width: 50, height: 50, borderRadius: 19, borderWidth: 1, borderColor: 'rgba(255,255,255,.74)', alignItems: 'center', justifyContent: 'center', ...Platform.select({ web: { boxShadow: webDepth.control } as any }) }, title: { color: colors.ink, fontFamily: serif, fontSize: 20, fontWeight: '700' }, subtitle: { color: colors.muted, fontSize: 8, marginTop: 3 }, choice: { minHeight: 70, borderRadius: 20, borderWidth: 1, borderColor: colors.line, backgroundColor: '#FFF', padding: 11, marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 11, ...Platform.select({ web: { boxShadow: webDepth.soft, transitionDuration: '150ms' } as any }) }, primary: { backgroundColor: colors.sageDeep, borderColor: colors.sageDeep }, choiceIcon: { width: 41, height: 41, borderRadius: 15, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center', ...Platform.select({ web: { boxShadow: webDepth.control } as any }) }, primaryIcon: { backgroundColor: 'rgba(255,255,255,.14)' }, choiceTitle: { color: colors.ink, fontSize: 10, fontWeight: '900' }, primaryTitle: { color: '#FFF' }, choiceBody: { color: colors.muted, fontSize: 8, lineHeight: 12, marginTop: 2 }, primaryBody: { color: '#DCEAE6' }, note: { color: colors.muted, fontSize: 7, lineHeight: 12, textAlign: 'center', marginTop: 12 } });
