import { MaterialCommunityIcons as NativeMaterialCommunityIcons } from '@expo/vector-icons';
import { Platform, Text, type TextProps } from 'react-native';

type IconName = keyof typeof NativeMaterialCommunityIcons.glyphMap;

const glyphFallbacks: Partial<Record<IconName, string>> = {
  'account-group-outline': '👥',
  'account-heart-outline': '💞',
  'account-lock-outline': '🔒',
  'account-multiple-outline': '👪',
  'account-plus-outline': '➕',
  'account-remove-outline': '➖',
  'account-switch-outline': '⇄',
  'alert-circle-outline': '⚠',
  'arrow-left': '←',
  'arrow-right': '→',
  'baby-bottle-outline': '🍼',
  'baby-face-outline': '👶',
  'bell-outline': '🔔',
  'bell-plus-outline': '🔔',
  'book-open-page-variant-outline': '📖',
  'bookmark-outline': '🔖',
  'calculator-variant-outline': '🧮',
  'calendar-blank-outline': '📅',
  'calendar-clock': '📅',
  'calendar-heart': '📅',
  'cellphone': '📱',
  'cellphone-link': '📱',
  'cellphone-lock': '📱',
  'chart-box-outline': '📊',
  'chart-line': '📈',
  'chart-line-variant': '📈',
  'chart-timeline-variant': '📈',
  'chart-timeline-variant-shimmer': '📈',
  check: '✓',
  'check-all': '☑',
  'check-circle': '✓',
  'check-circle-outline': '✓',
  'check-decagram-outline': '✓',
  'chevron-down': '⌄',
  'chevron-left': '‹',
  'chevron-right': '›',
  'circle-outline': '◯',
  'clipboard-text-clock-outline': '📋',
  'clock-outline': '⏱',
  'clock-plus-outline': '⏱',
  close: '×',
  'cloud-alert-outline': '☁',
  'cloud-check-outline': '☁',
  'cloud-off-outline': '☁',
  'cloud-outline': '☁',
  'cloud-sync-outline': '☁',
  'comment-check-outline': '💬',
  'comment-question-outline': '💬',
  'compare-horizontal': '⇄',
  'content-copy': '⧉',
  'content-save-outline': '💾',
  'creation-outline': '✨',
  'cup-water': '🥤',
  'dots-grid': '⋯',
  'dots-horizontal': '⋯',
  'emoticon-outline': '☺',
  'emoticon-sad-outline': '☹',
  'file-alert-outline': '📄',
  'file-check-outline': '📄',
  'file-document-outline': '📄',
  'file-hidden': '📄',
  'file-multiple-outline': '📄',
  'file-pdf-box': 'PDF',
  'file-plus-outline': '📄',
  'file-search-outline': '📄',
  'folder-heart-outline': '📁',
  'folder-outline': '📁',
  'food-apple-outline': '🍎',
  'food-outline': '🍽',
  'gesture-tap': '☝',
  'hand-heart-outline': '🤝',
  'heart-outline': '♡',
  'heart-pulse': '❤',
  'home-heart': '🏠',
  'human-handsup': '🙌',
  'human-male-height': '👤',
  'human-pregnant': '🤰',
  'information-outline': 'i',
  'link-lock': '🔗',
  'lock-outline': '🔒',
  'medical-bag': '🩺',
  'message-processing-outline': '💬',
  microphone: '🎤',
  'mother-nurse': '🤱',
  needle: '💉',
  'open-in-new': '↗',
  'pencil-outline': '✎',
  'phone-alert': '📱',
  pill: '💊',
  play: '▶',
  plus: '+',
  'plus-circle-outline': '+',
  'progress-clock': '⏳',
  refresh: '↻',
  'scale-bathroom': '⚖',
  'shield-account-outline': '🛡',
  'shield-alert-outline': '🛡',
  'shield-check-outline': '🛡',
  'shield-link-variant-outline': '🛡',
  'shield-lock-outline': '🛡',
  'shield-remove-outline': '🛡',
  'star-outline': '★',
  stethoscope: '🩺',
  stop: '■',
  'text-box-search-outline': '🔎',
  thermometer: '🌡',
  'thermometer-alert': '🌡',
  'timeline-text-outline': '⏳',
  'timer-outline': '⏱',
  'timer-sand': '⏳',
  'toy-brick-outline': '🧩',
  'trash-can-outline': '🗑',
  'tune-variant': '⚙',
  water: '💧',
  'water-outline': '💧',
  'weather-night': '🌙',
  'weather-sunset-up': '☀',
  'weather-windy': '〰',
};

function WebMaterialCommunityIcon({ name, size = 24, color, style, ...props }: TextProps & { name: IconName; size?: number; color?: string }) {
  const glyph = glyphFallbacks[name] ?? '◌';
  return (
    <Text
      {...props}
      accessibilityElementsHidden
      importantForAccessibility="no"
      style={[
        {
          color,
          fontSize: Math.max(12, size * 0.92),
          lineHeight: size,
          textAlign: 'center',
          fontWeight: '900',
          fontFamily: Platform.OS === 'web' ? 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' : undefined,
        },
        style,
      ]}
    >
      {glyph}
    </Text>
  );
}

const webFallback = Object.assign(WebMaterialCommunityIcon, {
  glyphMap: NativeMaterialCommunityIcons.glyphMap,
  font: NativeMaterialCommunityIcons.font,
  loadFont: NativeMaterialCommunityIcons.loadFont,
}) as unknown as typeof NativeMaterialCommunityIcons;

export const MaterialCommunityIcons = (Platform.OS === 'web' ? webFallback : NativeMaterialCommunityIcons) as typeof NativeMaterialCommunityIcons;
